<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Becky Collins">

<title>Introduction to Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Introduction to Statistics_files/libs/clipboard/clipboard.min.js"></script>
<script src="Introduction to Statistics_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Introduction to Statistics_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Introduction to Statistics_files/libs/quarto-html/popper.min.js"></script>
<script src="Introduction to Statistics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Introduction to Statistics_files/libs/quarto-html/anchor.min.js"></script>
<link href="Introduction to Statistics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Introduction to Statistics_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Introduction to Statistics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Introduction to Statistics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Introduction to Statistics_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Statistics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Becky Collins </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction-to-statistics" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-statistics">Introduction to Statistics</h2>
<p>Following the lecture you should now have some understanding of why statistics are important and how we use them to help us to answer scientific hypotheses.</p>
<p>In this session I am going to walk you through a very simple example of how to generate descriptive statistics, how to test for differences between groups, how to test for correlations and finally how to perform and interpret the results of both a univariate and multivariate linear regression.</p>
<p>At the end of the session there will be an exercise for you to have a go at that will not only get you to perform the appropriate statistics but also to combine this with some of the thematic mapping and testing of spatial autocorrelation you have been doing with Rich in the previous weeks. <strong>This lecture and practical have been written to cover both week 7 and week 8 of the teaching. If you complete everything this week then week 8 can be used as a support session for your assessment!</strong></p>
<p><strong>One quick note</strong> - There are as many different approaches to coding as there are people who code! You may notice significant differences between my way of working in R and what you have seen up to now! Part of this is experience - Rich has been coding significantly longer than I have, as I came to it only when necessity forced me away from my beloved GIS! I am also completely self-taught in this area, building skills as and when I needed them in a somewhat haphazard way!</p>
<p>The other part is personal preference - I loathe ggplot for mapping but love tmap; I do not like tidyverse but love base R. I tend not to use pipes but instead code in smaller chunks. It leaves me with a slightly busier global environment but means I find it much easier to track back when things go wrong. There is no one way to do things, simply what works for you!</p>
<p>The point here is that you may find this a slightly different style of handout than you have been used to, and that is good! You are being exposed to multiple ways to do things and multiple styles of teaching and learning! Embrace it!</p>
<p>Right - let’s get started!</p>
</section>
<section id="downloading-and-visualising-the-data" class="level2">
<h2 class="anchored" data-anchor-id="downloading-and-visualising-the-data">Downloading and visualising the data</h2>
<p>As in previous weeks, the first step is to make sure our required packages are installed and loaded and that we can download and open the data. Unlike in previous sessions I actually want you to manually download a zipped folder from blackboard and unzip it into your project directory.</p>
<p>The folder for this part of the practical is called “IMD_2019” and can be found on Blackboard under the same section you found this handout, ‘Intro to Statistics’.</p>
<p>Download the folder and unzip it directly into your project folder. As mentioned in previous sessions, shapefiles have multiple component parts to them and although we only OPEN one of the files, all of the other component files must be in the same place to allow the data to work!</p>
<p>Once the data is imported we would usually view the head of the data (the variable names and the top few rows) however this dataset has over 60 variables, meaning that printing the head of the data will not show us all we want to know.</p>
<p>Instead, we can get a list of the variable names and the data format. To do this we use <code>str()</code> to show us the structure of our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>installed <span class="ot">&lt;-</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"sf"</span>, <span class="st">"RColorBrewer"</span>, <span class="st">"ggplot2"</span>, <span class="st">"cowplot"</span>, <span class="st">"scales"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>install <span class="ot">&lt;-</span> pkgs[<span class="sc">!</span>(pkgs <span class="sc">%in%</span> installed)]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(install)) <span class="fu">install.packages</span>(install, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">lapply</span>(pkgs, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>IMD_2019 <span class="ot">&lt;-</span> IMD_2019 <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"IMD_2019_A.shp"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(IMD_2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sf [33,775 × 71] (S3: sf/tbl_df/tbl/data.frame)
 $ lsoa11cd  : chr [1:33775] "E01008162" "E01008163" "E01008164" "E01008165" ...
 $ lsoa11nm  : chr [1:33775] "Gateshead 027A" "Gateshead 028A" "Gateshead 027B" "Gateshead 011A" ...
 $ lsoa11nmw : chr [1:33775] "Gateshead 027A" "Gateshead 028A" "Gateshead 027B" "Gateshead 011A" ...
 $ st_areasha: num [1:33775] 483382 295152 224209 315426 1431145 ...
 $ st_lengths: num [1:33775] 4462 3974 3045 3463 5717 ...
 $ IMD_Rank  : num [1:33775] 11206 6621 2081 1341 6148 ...
 $ IMD_Decile: num [1:33775] 4 3 1 1 2 2 3 3 1 3 ...
 $ LSOA01NM  : chr [1:33775] "Gateshead 027A" "Gateshead 028A" "Gateshead 027B" "Gateshead 011A" ...
 $ LADcd     : chr [1:33775] "E08000037" "E08000037" "E08000037" "E08000037" ...
 $ LADnm     : chr [1:33775] "Gateshead" "Gateshead" "Gateshead" "Gateshead" ...
 $ IMDScore  : num [1:33775] 24.3 33.1 50.7 56.1 34.3 ...
 $ IMDRank0  : num [1:33775] 11206 6621 2081 1341 6148 ...
 $ IMDDec0   : num [1:33775] 4 3 1 1 2 2 3 3 1 3 ...
 $ IncScore  : num [1:33775] 0.129 0.165 0.299 0.328 0.184 0.219 0.147 0.11 0.299 0.178 ...
 $ IncRank   : num [1:33775] 12600 9233 2240 1477 7757 ...
 $ IncDec    : num [1:33775] 4 3 1 1 3 2 4 5 1 3 ...
 $ EmpScore  : num [1:33775] 0.093 0.154 0.215 0.236 0.131 0.156 0.104 0.135 0.224 0.112 ...
 $ EmpRank   : num [1:33775] 13843 6188 2486 1701 8396 ...
 $ EmpDec    : num [1:33775] 5 2 1 1 3 2 4 3 1 4 ...
 $ EduScore  : num [1:33775] 17.1 31.5 55 57.1 30.6 ...
 $ EduRank   : num [1:33775] 15771 8001 2393 2086 8319 ...
 $ EduDec    : num [1:33775] 5 3 1 1 3 3 4 2 2 2 ...
 $ HDDScore  : num [1:33775] 0.668 0.919 1.692 1.48 1.644 ...
 $ HDDRank   : num [1:33775] 7203 4878 887 1562 994 ...
 $ HDDDec    : num [1:33775] 3 2 1 1 1 1 1 2 1 1 ...
 $ CriScore  : num [1:33775] 1.325 1.452 1.15 1.739 0.479 ...
 $ CriRank   : num [1:33775] 1648 1201 2524 499 9359 ...
 $ CriDec    : num [1:33775] 1 1 1 1 3 1 3 1 1 2 ...
 $ BHSScore  : num [1:33775] 23.2 14 18.2 25.1 21.6 ...
 $ BHSRank   : num [1:33775] 12966 24212 18894 11047 14726 ...
 $ BHSDec    : num [1:33775] 4 8 6 4 5 8 6 8 8 8 ...
 $ EnvScore  : num [1:33775] 6.45 16.87 13.54 7.05 23.12 ...
 $ EnvRank   : num [1:33775] 27850 17695 20540 27209 13039 ...
 $ EnvDec    : num [1:33775] 9 6 7 9 4 5 2 4 5 4 ...
 $ IDCScore  : num [1:33775] 0.149 0.113 0.388 0.475 0.27 0.202 0.241 0.057 0.388 0.263 ...
 $ IDCRank   : num [1:33775] 14155 17790 1688 476 5848 ...
 $ IDCDec    : num [1:33775] 5 6 1 1 2 4 3 8 1 2 ...
 $ IDOScore  : num [1:33775] 0.35 0.337 0.294 0.318 0.537 0.356 0.384 0.21 0.405 0.243 ...
 $ IDORank   : num [1:33775] 3043 3375 4936 3998 421 ...
 $ IDODec    : num [1:33775] 1 2 2 2 1 1 1 3 1 3 ...
 $ CYPScore  : num [1:33775] 0.156 0.633 1.587 1.338 0.501 ...
 $ CYPRank   : num [1:33775] 13603 7243 776 1655 8840 ...
 $ CYPDec    : num [1:33775] 5 3 1 1 3 2 2 1 2 1 ...
 $ ASScore   : num [1:33775] 0.287 0.372 0.394 0.468 0.384 0.353 0.296 0.37 0.419 0.41 ...
 $ ASRank    : num [1:33775] 17477 8915 7233 3266 7902 ...
 $ ASDec     : num [1:33775] 6 3 3 1 3 4 6 3 2 2 ...
 $ GBScore   : num [1:33775] 0.327 -0.983 -0.236 0.224 -0.394 ...
 $ GBRank    : num [1:33775] 10365 29680 19867 11920 22437 ...
 $ GBDec     : num [1:33775] 4 10 7 4 7 9 8 10 10 10 ...
 $ WBScore   : num [1:33775] 0.407 1.025 0.938 1.198 1.998 ...
 $ WBRank    : num [1:33775] 13192 10443 10797 9715 6940 ...
 $ WBDec     : num [1:33775] 5 4 4 3 3 4 3 4 3 3 ...
 $ IndScore  : num [1:33775] -1.358 -0.393 -0.184 -1.785 0.119 ...
 $ IndRank   : num [1:33775] 31029 22465 19383 32224 14608 ...
 $ IndDec    : num [1:33775] 10 7 6 10 5 6 1 4 8 3 ...
 $ OutScore  : num [1:33775] -0.019 0.607 -0.019 0.118 0.585 ...
 $ OutRank   : num [1:33775] 15620 7353 15612 13337 7551 ...
 $ OutDec    : num [1:33775] 5 3 5 5 3 3 4 4 2 5 ...
 $ TotPop    : num [1:33775] 2706 2128 1506 1456 1508 ...
 $ DepChi    : num [1:33775] 327 626 274 299 33 283 212 660 251 330 ...
 $ Pop16_59  : num [1:33775] 2076 1179 996 908 1256 ...
 $ Pop60+    : num [1:33775] 303 323 236 249 219 309 322 186 362 164 ...
 $ WorkPop   : num [1:33775] 2116 1108 1005 886 1356 ...
 $ RGN24CD   : chr [1:33775] "E12000001" "E12000001" "E12000001" "E12000001" ...
 $ RGN24NM   : chr [1:33775] "North East" "North East" "North East" "North East" ...
 $ BNG_E     : num [1:33775] 417315 417315 417315 417315 417315 ...
 $ BNG_N     : num [1:33775] 6e+05 6e+05 6e+05 6e+05 6e+05 ...
 $ LONG      : num [1:33775] -1.73 -1.73 -1.73 -1.73 -1.73 ...
 $ LAT       : num [1:33775] 55.3 55.3 55.3 55.3 55.3 ...
 $ GlobalID  : chr [1:33775] "4885458b-5614-4e44-87c5-26d5755e24c1" "4885458b-5614-4e44-87c5-26d5755e24c1" "4885458b-5614-4e44-87c5-26d5755e24c1" "4885458b-5614-4e44-87c5-26d5755e24c1" ...
 $ geometry  :sfc_MULTIPOLYGON of length 33775; first list element: List of 1
  ..$ :List of 1
  .. ..$ : num [1:45, 1:2] 426699 426704 426692 426722 426735 ...
  ..- attr(*, "class")= chr [1:3] "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "names")= chr [1:70] "lsoa11cd" "lsoa11nm" "lsoa11nmw" "st_areasha" ...</code></pre>
</div>
</div>
<p>This shows us that we have some character variables that represent the area names and codes, or identifiers, and a long series of numeric variables that represent the Index of Multiple Deprivation (IMD) data. This also shows us that some of our numeric data is integer data (non-decimal numbers) and some is continuous data (decimal numbers).</p>
<p>To give you a little background, this data measures a series of variables that are considered to be indicators of deprivation. The higher a ‘score’ value, the higher the deprivation is in that area. The lower the ‘rank’ value is, the higher the deprivation - as areas are ranked from most deprived (1) to least deprived (32844). The variables that begin IMD are a combined measure of all of the indicator indices, whereas each individual indicator has it’s own set of values. Finally the ‘decile’ variables group each LSOA into deciles where the higher the deprivation the lower the decile (the place ranked most deprived would have a decile of 1, while the place ranked least deprived would have a decile of 10).</p>
</section>
<section id="mapping-the-data" class="level2">
<h2 class="anchored" data-anchor-id="mapping-the-data">Mapping the Data</h2>
<p>Let’s begin by plotting the most simple map of the “IMDRank0” variable using some lightly edited code from a previous practical.</p>
<p>You may notice that I have added <code>color = NA</code> inside the <code>geom_sf()</code> function. This is because the <code>geom_sf()</code> function would plot the outlines of the polygons within the shapefile, however on a map of this national scale and with polygons that are so small by comparison to the coverage area, the polygon outlines just create a large mass of grey. By including the <code>color = NA</code> argument I have suppressed the lines to make the fill colours easier to see.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">fill =</span> IMDRank0)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="st">"IMD Rank"</span>, <span class="at">palette =</span> <span class="st">"RdYlBu"</span>, <span class="at">direction =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"English Index of Multiple Deprivation"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"2019 IMD Rank by LSOA"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: data.gov.uk"</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/initial%20map-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>But this doesn’t really do much to help us understand the statistics of the data. It was just a quick warm up exercise before we dive in!</p>
</section>
<section id="summarising-data" class="level1">
<h1>Summarising Data</h1>
<section id="measures-of-central-tendency-and-measures-of-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-central-tendency-and-measures-of-dispersion">Measures of Central Tendency and Measures of Dispersion</h3>
<p>As in the lecture, descriptive statistics are methods by which we can begin to describe the middle of our data (measures of central tendency) and the spread of our data (measures of dispersion).</p>
<p>R is very handy for providing very quick methods to acquire summary statistics in the form of the <code>summary()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(IMD_2019<span class="sc">$</span>IMDScore)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.541   9.815  17.392  21.460  29.217  92.735 </code></pre>
</div>
</div>
<p>The output of this function tells us a great deal about the data. Firstly, we can establish the range of our data by subtracting the Min. value from the Max. value, telling us that we have a range of 92.194. We can also see that the mean is higher than the median, indicating that there are some high values that are skewing our mean upwards away from the middle value.</p>
<p>This doesn’t, however, tell us much about the dispersion of our data. To establish this we can calculate the Variance, it’s square root the Standard Deviation and the Coefficient of Variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Variance <span class="ot">&lt;-</span> <span class="fu">var</span>(IMD_2019<span class="sc">$</span>IMDScore)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>S.Dev <span class="ot">&lt;-</span> <span class="fu">sd</span>(IMD_2019<span class="sc">$</span>IMDScore)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>CoV <span class="ot">&lt;-</span> <span class="fu">sd</span>(IMD_2019<span class="sc">$</span>IMDScore<span class="sc">/</span><span class="fu">mean</span>(IMD_2019<span class="sc">$</span>IMDScore))<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>Variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 232.2371</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>S.Dev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.23933</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>CoV</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 71.0124</code></pre>
</div>
</div>
<p>The (relatively) high values of the variance and the standard deviation and the high percentage Coefficient of Variation tell us that there is considerable spread of our data around the mean.</p>
<p>Visually, the best way to represent this is on a histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Hist <span class="ot">&lt;-</span> IMD_2019 <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> IMDScore)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_rug</span>(<span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">17.4</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">21.4</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"IMD Score"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"England IMD Scores 2019"</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_colour_discrete</span>(<span class="at">name =</span> <span class="st">"LADnm"</span>) <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>())</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>Hist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/histogram-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can see that I have added two vertical lines to the histogram to represent the median (red dashed) and mean (blue dotted) values. This, along with the shape of our data tell us that the data has a positive (or right) skew - with more of the data appearing to the right of the peak, or a prevalence of high values within the dataset. You can also see that the data is spread out and does not cluster closely around either median or mean values.</p>
</section>
<section id="outliers" class="level3">
<h3 class="anchored" data-anchor-id="outliers">Outliers</h3>
<p>It is often a good idea to establish whether your data contains any outliers. An outlier is typically considered to be a value that is more than 1.5 x the IQR (interquartile range) away from the Q1 (lower) or Q3 (upper) values of your dataset.</p>
<p>We already have the Q1 and Q3 values thanks to the outcome of our <code>summary()</code> function. We can use another function <code>IQR()</code> to calculate the IQR of our data. From there we can do some simple maths to determine whether our variable contains any outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">=</span> <span class="fu">as.vector</span>(<span class="fu">summary</span>(IMD_2019<span class="sc">$</span>IMDScore))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>IQR_mult <span class="ot">&lt;-</span> <span class="fu">IQR</span>(IMD_2019<span class="sc">$</span>IMDScore) <span class="sc">*</span> <span class="fl">1.5</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>Lower_bound <span class="ot">=</span> summary_stats[<span class="dv">2</span>] <span class="sc">-</span> IQR_mult</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>Upper_bound <span class="ot">=</span> summary_stats[<span class="dv">5</span>] <span class="sc">+</span> IQR_mult</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>Lower_bound</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -19.288</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Upper_bound</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58.32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this returns the sum of a logical test where any value greater than our upper bound gets a value of 1 and all other values get 0. It is a quick way of counting the number of observations that meet a specific condition.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(IMD_2019<span class="sc">$</span>IMDScore <span class="sc">&gt;</span> <span class="fl">58.32</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1085</code></pre>
</div>
</div>
<p>This gives up the upper and lower bounds beyond which a value is deemed to <em>potentially</em> be an outlier and allows us to identify that there are 1085 potential outliers in our dataset.</p>
<p>We will come back to that word potentially in a moment.</p>
<p>A boxplot is a useful way to show some of the key descriptive statistics as it displays the median value (the black line), the middle 50% of the data (the box), the Minimum and Maximum bounds based on the IQR * 1.5 rule (the whiskers) and any outliers (dots beyond the whiskers).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Box <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> IMDScore)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"IMD_Score"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Spread of IMD Score"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>Box</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s go back to that word <em>potentially</em>. The method we have used to identify the presence of outliers to this point (identifying the upper and lower bounds and plotting on a boxplot) are both using arbitrary methods and values to define what an outlier is. However, should we arbitrarily dismiss approx 3% of our data?</p>
<p>Let’s take another look at the histogram and the boxplot together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(Hist, Box, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/hist%20and%20box%20side%20by%20side-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see from these two plots that there are no breaks in the data as you move into the tail of the histogram and that the outlier points are clustered very closely together from the end of the whisker. These are indicators that, while the outlier detection method may flag these points as potential outliers, that may not necessarily mean that they are outliers.</p>
<p>To help make this a little clearer - imagine that you were creating a histogram of global income. This is a measure of a known value, and while the traditional method of IQR*1.5 would cut off the Elon Musk’s and the Jeff Bezos of the world, they are not actually outliers because their income does represent an actual measurement. However, if you were performing a laboratory analysis of the concentration of nitrogen in a water sample, a sudden high value in the billions while all others were in the 10s of thousands would certainly be identified as an outlier caused by error.</p>
<p>Any decision you make, whether to keep or remove potential outliers, should be made with an understanding of the data you are working with and the statistical test you are planning to perform.</p>
</section>
</section>
<section id="inferential-statistics" class="level1">
<h1>Inferential Statistics</h1>
<p>There are a vast number of potential statistical tests that can be performed on a wide variety of different data types, but for the purposes of this session I am going to break them into two concepts:</p>
<p><strong>Looking for differences between groups</strong> - e.g.&nbsp;comparing between different genders, different age groups, different climate models, different river catchments etc</p>
<p><strong>Looking for relationships between variables</strong> - e.g.&nbsp;if temperature increases do drink sales increase? If river flow increases does dissolved oxygen decrease?</p>
<p>We are going to start by looking for differences between groups - initially to see whether there is a statistically significant difference in the deprivation scores of the North East and the West Midlands and then expand that across all groups.</p>
<section id="t-test-or-mann-whitney-u-test" class="level3">
<h3 class="anchored" data-anchor-id="t-test-or-mann-whitney-u-test">T-Test or Mann-Whitney U Test</h3>
<p>When comparing the averages of two groups to determine whether they are statistically significantly different, we usually use the T-Test. This, in simple terms, compares the mean of the two groups and determines whether that difference is statistically significant. However, the T-Test is what is known as a Parametric test - one that is optimised for normally distributed data.</p>
<p>We have determined - albeit only visually - that this data is not normally distributed. The mean and median are different and the histogram has a right skew (there are more values to the right of the peak than to the left). In this instance we would instead use the non-parametric version - the Mann-Whitney U test. The difference between the T-test and the MWU test is that the MWU test compares the ranks of the data rather than the means.</p>
<p>First, we need to extract the two regions we are interested in as the MWU test only works with two groups, then we can execute the test. Confusingly, the function to perform the MWU test is called <code>wilcox.test()</code>! Once we have the results it would also be useful to see the calculated mean and median of each group to see what the values actually are.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>NEandWM <span class="ot">&lt;-</span> IMD_2019 <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RGN24NM <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"North East"</span>, <span class="st">"West Midlands"</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">formula =</span> IMDScore<span class="sc">~</span>RGN24NM, <span class="at">data =</span> NEandWM, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  IMDScore by RGN24NM
W = 3299178, p-value = 7.713e-09
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>NEandWM <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(RGN24NM) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_IMD =</span> <span class="fu">mean</span>(IMDScore, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_IMD =</span> <span class="fu">median</span>(IMDScore, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  RGN24NM       mean_IMD median_IMD
  &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
1 North East        28.0       24.6
2 West Midlands     24.6       20.3</code></pre>
</div>
</div>
<p>The results of this test may look very confusing, and they can be a bit challenging to get your head around initially. The values of interest to us here are the W statistic and the p-value.</p>
<p>The W statistic is the sum of the ranks of your first group (in this case North East because it appears first in the dataset) if all of the values were lined up in order and the values of their rank position was summed. For example, look at the table below. In this example, the North East has positions 3 + 5 + 6 + 7 giving them a rank sum of 21 while the West Midlands has positions 1 + 2 + 4 + 8 giving them a rank sum of 15. That lower rank sum tells you that the West Midlands has more values in the lower range of our dataset than the North East.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Region</th>
<th>Value</th>
<th>Position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>West Midlands</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>West Midlands</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td>North East</td>
<td>3</td>
<td>3</td>
</tr>
<tr class="even">
<td>West Midlands</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<td>North East</td>
<td>5</td>
<td>5</td>
</tr>
<tr class="even">
<td>North East</td>
<td>6</td>
<td>6</td>
</tr>
<tr class="odd">
<td>North East</td>
<td>7</td>
<td>7</td>
</tr>
<tr class="even">
<td>West Midlands</td>
<td>8</td>
<td>8</td>
</tr>
</tbody>
</table>
<p>This value doesn’t really mean much on it’s own as it is a function of the number of possible positions (or observations) in the data, but the p-value tells us the likelihood that this W value would be generated if the groups came from the same distribution (i.e.&nbsp;had the same extremes and the same shape).</p>
<p>It may be helpful to also view the distribution on a histogram to make this easier to understand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(NEandWM, <span class="fu">aes</span>(<span class="at">x =</span> IMDScore, <span class="at">fill =</span> RGN24NM)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"IMD Score Distributions by Region"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"IMD Score"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Region"</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/regional%20hist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that there are significantly more West Midlands areas with lower IMD scores than the North East, and that the very small p-value of the test also suggests that there is a statistically significant difference between the two groups.</p>
</section>
<section id="testing-multiple-groups-with-anova-or-kruskal-wallis" class="level3">
<h3 class="anchored" data-anchor-id="testing-multiple-groups-with-anova-or-kruskal-wallis">Testing multiple groups with ANOVA or Kruskal Wallis</h3>
<p>We can also do a similar analysis across multiple groups using the ANOVA (parametric) or the Kruskal Wallis (non-parametric) tests. The Kruskal Wallis tests is very similar to the MWU test in that it also groups all of the data together and then ranks the values of each rank before summing those values. The slight difference is that the Chi-Squared test statistic actually uses the mean rank rather than the sum of the rank for comparison between groups so you can consider the statistic as the variance of the mean ranks. The smaller the value the more similar the mean rank across groups. but the larger the value the greater the differences between the values.</p>
<p>Again, this is only really of value alongside the p-value, which tests the likelihood that the chi squared statistic could be generated from a random distribution. In the code below I have changed from a histogram to a density plot because they are slightly easier to interpret when overlaying multiple different datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(<span class="at">formula =</span> IMDScore <span class="sc">~</span> RGN24NM, <span class="at">data =</span> IMD_2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  IMDScore by RGN24NM
Kruskal-Wallis chi-squared = 2466.5, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> IMDScore, <span class="at">fill =</span> RGN24NM)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"IMD Score Distributions by Region"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"IMD Score"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Region"</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/kw%20test-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The only problem with this test is that it tells us there is a statistically significant difference between groups but doesn’t tell us which groups are statistically different. To establish this information we need to perform what is known as a post hoc test - a test that unpicks the results of the Kruskal Wallis and give more detail about which groups are different or similar. Traditionally the Dunn test is used as the post hoc test for a Kruskal Wallis test, but in this example we are going to go with the slightly quicker pairwise MWU test approach, which performs a series of MWU tests on all possible pairs of groups and then reports the results as a matrix which we will then turn into a heat map of the significant and not significant pairings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Run the post hoc test</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>post_hoc <span class="ot">&lt;-</span> <span class="fu">pairwise.wilcox.test</span>(IMD_2019<span class="sc">$</span>IMDScore, IMD_2019<span class="sc">$</span>RGN24NM,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the p-values from the matrix produced by the pairwise test</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>pvals_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as.table</span>(post_hoc<span class="sc">$</span>p.value)) <span class="sc">%&gt;%</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Freq)) <span class="sc">%&gt;%</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Region1 =</span> Var1, <span class="at">Region2 =</span> Var2, <span class="at">p_value =</span> Freq)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Classify the p-values into significant or not significant</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>pvals_df <span class="ot">&lt;-</span> pvals_df <span class="sc">%&gt;%</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Significance =</span> <span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Significant"</span>, <span class="st">"Not Significant"</span>))</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a binary heat map showing which regions are significantly similar/different</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pvals_df, <span class="fu">aes</span>(<span class="at">x =</span> Region1, <span class="at">y =</span> Region2, <span class="at">fill =</span> Significance)) <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Significant"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Not Significant"</span> <span class="ot">=</span> <span class="st">"grey80"</span>)) <span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Significant Pairwise Differences Between Regions"</span>,</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Region 1"</span>,</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Region 2"</span>,</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Result"</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid =</span> <span class="fu">element_blank</span>()</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/KW%20post%20hoc%20test-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What this shows us is that only the pairs North East and North West and West Midlands and Yorkshire and the Humber are significantly similar to one another. All other pairs of regions are significantly different from one another.</p>
</section>
<section id="relationships-between-variables" class="level3">
<h3 class="anchored" data-anchor-id="relationships-between-variables">Relationships between variables</h3>
<p>Now we have spent some time looking at similarities and differences between groups, we can start to look for relationships between variables. Often, relationships between continuous variables can be established using correlations and scatter plots.</p>
<p><strong>Quick note -</strong> As touched on in the lecture, most statistics require that data be ‘independent’, or unrelated to one another, in order for the conclusions you draw from those statistics to be meaningful and robust. Because the IMD Rank, Score, and Decile values in this dataset are made up of a combination of all of the other variables they cannot be considered to be independent so from now on we will be looking for relationships between some of the different indicator variables used to make up the overall IMD value. One could argue that, because all of these variables are measures of deprivation then can any of them truly be independent of one another…however for now let’s assume that they are!</p>
</section>
<section id="scatter-plots" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plots">Scatter Plots</h3>
<p>One of the main drivers of deprivation is income and, in simple terms, one of the main indicators of income is education level. So, let’s look and see whether this data shows a similar relationship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>IMD_2019 <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> EduScore, <span class="at">y =</span> IncScore)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>(<span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education Deprivation Score"</span>, <span class="at">y =</span> <span class="st">"Income Deprivation Score"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"The relationship between income and education deprivation in England 2019"</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/scatter%20plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see from the plot, where the education deprivation score is low (indicating a low level of education deprivation - or a high level of education opportunity) so is the income deprivation score (indicating a low level of income deprivation - or a high level of income attainment).</p>
<p>This is a positive relationship (as one increases so does the other). However, while the plot shows us that there appears to be a correlation, the only way to test that the relationship is statistically significant is via a statistical test - namely the Pearson (parametric) or Spearmans (non-parametric) tests. The spearmans rank test that we are using here once again ranks our two variables values (separately this time rather than combining them together) and then calculates the variance of each rank from the mean to determine how the data varies individually and then how similar those two variances are.</p>
<p>In this example I have used the argument <code>exact = FALSE</code> to suppress a warning about ties. Ties are what happens when there are repeat values in your data and so multiple observations are given the same rank. It doesn’t prevent the test from working, but it means that the p-value is an approximation and not an exact value. This can be problematic when the p-value is very close to the chosen significance level but in this instance an approximation is totally fine.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> IMD_2019<span class="sc">$</span>IncScore, IMD_2019<span class="sc">$</span>EduScore, <span class="at">method =</span> <span class="st">"spearman"</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  IMD_2019$IncScore and IMD_2019$EduScore
S = 1.194e+12, p-value &lt; 2.2e-16
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.8140661 </code></pre>
</div>
</div>
<p>The output of the Spearman Rank correlation is the rho value. This is a value from +1 (perfect positive correlation - when one increases the other also increases) to -1 (perfect negative correlation - when one increases the other decreases). A rho value of 0 indicates that there is no correlation, the variables increase independently of one another.</p>
<p>Correlations are great for telling us how two variables relate to each other, but you cannot use a correlation as a predictor. In order to begin to make predictions you need to carry out regression analysis.</p>
</section>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<section id="univariate-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="univariate-linear-regression">Univariate Linear Regression</h3>
<p>If you want to use one variable to predict another you need to use linear regression. The equation for linear regression is shown below:</p>
<p><span class="math display">\[
Y_i = \beta_0+\beta_1X_i+\varepsilon_i
\]</span></p>
<p>where:</p>
<p><span class="math inline">\(Yi\)</span> = the value of the dependent variable (Y) at the <span class="math inline">\(i\)</span>th observation or location</p>
<p><span class="math inline">\(\beta_0\)</span> = the intercept value (the value of y if x is zero)</p>
<p><span class="math inline">\(\beta_1\)</span> = the slope coefficient of the independent variable <span class="math inline">\(X\)</span></p>
<p><span class="math inline">\(X_i\)</span> = The value of the independent variable at the <span class="math inline">\(i\)</span>th observation or location</p>
<p><span class="math inline">\(\varepsilon_i\)</span> = The error value (or residual) at the <span class="math inline">\(i\)</span>th observation or location</p>
<p>With a correlation it does not matter which variable you treat as the dependent (or the response variable), however with regression it does matter. Your dependent variable (DV) is <em>dependent</em> on the independent (predictor) variable. It is the dependent variable you wish to be able to predict from your regression equation.</p>
<p>Let’s take the example we just used of Education Deprivation and Income Deprivation. We can generate a linear regression equation that would allow us to predict the value of the dependent variable (Income Deprivation) from the value of the independent variable (Education Deprivation).</p>
<p>First, we create our linear regression model. If you look at the documentation for the <code>lm()</code> function using <code>?lm()</code> you will see that the first argument for a linear model is <code>formula</code>. Further down the guidance there is a section that states “Models for&nbsp;<code>lm</code>&nbsp;are specified symbolically. A typical model has the form&nbsp;<code>response ~ terms</code>&nbsp;where&nbsp;<code>response</code>&nbsp;is the (numeric) response vector and&nbsp;<code>terms</code>&nbsp;is a series of terms which specifies a linear predictor for&nbsp;<code>response</code>.”. This means that you must first specify your dependent variable and then your independent variable(s). This is very important, because you will be used to writing things as x y, however in linear regression the y variable is the dependent variable, so you must start with that.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>linear_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> IncScore <span class="sc">~</span> EduScore, <span class="at">data =</span> IMD_2019)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = IncScore ~ EduScore, data = IMD_2019)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.230807 -0.030159 -0.008674  0.024081  0.309499 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 3.669e-02  4.278e-04   85.76   &lt;2e-16 ***
EduScore    4.194e-03  1.509e-05  277.86   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05134 on 33773 degrees of freedom
Multiple R-squared:  0.6957,    Adjusted R-squared:  0.6957 
F-statistic: 7.721e+04 on 1 and 33773 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this summary you can see the <code>call</code> at the top, which reminds you of the components of your model, before you get a summary of the <code>residuals</code> which we will come back to in a moment. The next section is possibly the most important - the <code>coefficients</code>.</p>
<p>This contains the value of the intercept ($\beta_0$) and the value of the slope coefficient for your IVs. Both of these are stored in the ‘Estimates’ column. It also provides a p-value for each IV telling you whether each IV is statistically significantly contributing to the variation in your DV.</p>
<p>So in this model the Intercept is 0.0367. This means that where the EduScore is zero you can expect the IncScore to be 0.0367.</p>
<p>The value of the slope coefficient of education score is 0.00419. What this means is that “for a 1 unit change in the independent variable, EduScore, the dependent variable, IncScore, will change by 0.00419 in the same direction”. If the coefficient was negative the change would occur in the opposite direction. We can interpret this as “If the education deprivation score increases by 1, the income deprivation score will increase by 0.00419”. This shows us that as education score increases so does income deprivation score.</p>
<p>The intercept and slope represent and linear relationship between our two variables. Let’s quickly plot this on the previous scatter plot of our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>IMD_2019 <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> EduScore, <span class="at">y =</span> IncScore)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">0.0367</span>, <span class="at">slope =</span> <span class="fl">0.00419</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>(<span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Education Deprivation Score"</span>, <span class="at">y =</span> <span class="st">"Income Deprivation Score"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"The relationship between income and education deprivation in England 2019"</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/scatter%20with%20model%20line-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see from the plot that this line runs right through the densest parts of our data and follows the positive trend very clearly. However, there is lots of variation around that line.</p>
<p>The next section of the model output tells us the R-Squared values and the p-value. The multiple R-squared value does not account for model complexity so when you have only 1 IV it will be the same as the adjusted R-squared value, however if you add more IVs to your model the multiple R-squared will always either stay the same or increase even if your new variable adds nothing to the predictive power of your model. So instead, you should always look at the Adjusted R-squared, which adds a function to account for model complexity when there are more than one IV.</p>
<p>In this model our Adjusted R-squared value is 0.696. This means that 69.6% of the variation in our DV can be explained by our IV. Another way of thinking of it is that 30.4% of the variation in our DV remains unexplained by our IV. Given the spread of our data around our modeled line, that seems to be reasonable. If the model had a perfect R-squared of 1 there would be no variation around the line at all.</p>
<p>That unexplained variation can be represented by our residuals - the difference between the actual value of our DV and the predicted value based on our model.</p>
<p>First, let’s put our model values into the equation. Note that Y now wears a little hat (it is actually called the hat symbol). This indicates that we are now looking at a <em>predicted</em> value of Y and not an <em>actual</em> value of Y (as shown in the previous equation).</p>
<p><span class="math display">\[
\hat{Y}_i = 0.0367 + 0.00419X_i
\]</span></p>
<p>The way to think about this is “the predicted value of Y at i is equal to 0.0367 plus 0.00419 multiplied by the value of X at i”. This is how we can now take the information from our linear model and begin to use it as a prediction method.</p>
<p>So, let’s say the value of X at i was 1 the equation would be:</p>
<p><span class="math display">\[
\hat{Y}_i = 0.0367 + (0.00419 * 1)
\]</span></p>
<p>or</p>
<p><span class="math display">\[
\hat{Y}_i = 0.0367 + 0.00419
\]</span></p>
<p>or</p>
<p><span class="math display">\[
\hat{Y}_i = 0.0409
\]</span></p>
<p>The <code>lm()</code> function actually calculates predicted Y values for all values of the IV as part of it’s model and it uses them to then calculate our residuals, the difference between an actual Y value and the predicted Y value at each value of X. A residual is essentially:</p>
<p><span class="math display">\[
residual = Y_i - \hat{Y}_i
\]</span></p>
<p>or the actual (observed) value of Y minus the predicted value of Y. A negative residual is one where the model has over-predicted (the actual value of Y is smaller than the predicted value of Y) while a positive residual is one where the model has under-predicted (the actual value of Y is larger than the predicted value of Y).</p>
<p>We can get a summary of our residuals by calling the residuals component of our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_mod<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.230807 -0.030159 -0.008674  0.000000  0.024081  0.309499 </code></pre>
</div>
</div>
<p>We can see that the mean of our residuals is zero - this is to be expected in an unbiased model as it means that there is no systematic under or over prediction of our model. It also helps to confirm that the data is linear - if the data would be better represented by a curved model you would likely see deviation from the zero mean in the residuals.</p>
<p>We can use a density plot to view the distribution of the residuals. First we need to extract the residuals from the model and add them to the original dataframe as a variable for plotting. While we’re doing that we can also extract the fitted values as we will need those later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>IMD_2019 <span class="ot">&lt;-</span> IMD_2019 <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">predicted =</span> <span class="fu">fitted</span>(linear_mod),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">residuals =</span> <span class="fu">resid</span>(linear_mod)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> residuals)) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residual Distribution"</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Residual"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/residuals%20density%20plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our density plot shows that the peak is just slightly to the left of zero, but that the distribution is largely normal. Non-normally distributed residuals indicate that the model over- or under-predicts more often and can show that there are systematic errors in the model definition.</p>
<p>Another test we can use is the residuals vs fitted plot. This plots the residual values against the predicted (fitted) values and allows you to visually check that the spread of the residuals is the same at the bottom and top ends of the fitted values. If the points cluster around the horizontal line at both ends of the x axis then your residuals are homoskedastic - the spread of the residual error in your model is consistent across the range of your fitted values and the model is not systematically better in lower ranges than higher (or vice versa).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> predicted, <span class="at">y =</span> residuals)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals vs Fitted Values"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fitted Values (Predicted Y)"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Residuals (eᵢ)"</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/residuals%20vs%20fitted%20plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we can see from the plot, this model is homoskedastic, visually the spread of the residuals is approximately equal along the full length of the x-axis.</p>
<p>There are lots of other diagnostic tests you can use for linear regression models and this is a good area around which you can do some additional reading.</p>
</section>
<section id="multivariate-regression" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-regression">Multivariate Regression</h3>
<p>Now that you have some experience of univariate regression you can move into multivariate regression. Multivariate regression adds additional independent variables to your model to provide more explanatory power. Multivariate regression can be represented by the equation below:</p>
<p><span class="math display">\[
Y_i = \beta_0+\beta_1 X_{1i}+\beta_2 X_{2i}+\dots+\beta_p X{pi} +\varepsilon_i
\]</span></p>
<p>where:</p>
<p><span class="math inline">\(Yi\)</span> = the value of the dependent variable (Y) at the <span class="math inline">\(i\)</span>th observation or location</p>
<p><span class="math inline">\(\beta_0\)</span> = the intercept value (the value of y if all IVs are zero)</p>
<p><span class="math inline">\(\beta_1, \beta_2,\dots,\beta_p\)</span> = the slope coefficient of independent variables</p>
<p><span class="math inline">\(X_{1i}, X_{2i}\dots,X_{pi}\)</span> = The value of the independent variable at the <span class="math inline">\(i\)</span>th observation or location</p>
<p><span class="math inline">\(\varepsilon_i\)</span> = The error value (or residual) at the <span class="math inline">\(i\)</span>th observation or location</p>
<p>Multivariate regressions returns coefficient values that represent the slope of the line for each independent variable <em>if all other variables were to remain constant</em>. It isolates the effect of each IV to provide a mechanism by which to predict how a change in one IV would affect the DV.</p>
<p>Let’s take a look at what this means in practice. We’re going to go back to the model we created earlier and look at the effect of education deprivation on income deprivation but this time we are also going to add employment deprivation as an explanatory (or independent) variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>multi_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> IncScore <span class="sc">~</span> EduScore <span class="sc">+</span> EmpScore, <span class="at">data =</span> IMD_2019)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multi_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = IncScore ~ EduScore + EmpScore, data = IMD_2019)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.228763 -0.015668 -0.002497  0.012322  0.202238 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -3.422e-03  2.594e-04  -13.19   &lt;2e-16 ***
EduScore     7.289e-04  1.392e-05   52.36   &lt;2e-16 ***
EmpScore     1.158e+00  3.840e-03  301.49   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02672 on 33772 degrees of freedom
Multiple R-squared:  0.9176,    Adjusted R-squared:  0.9176 
F-statistic: 1.879e+05 on 2 and 33772 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The output of the model summary is very similar to a univariate model just with extra variables in the coefficients table. We can see that all of our p-values are significant, so our model overall is significant and each of our IVs are statistically significantly contributing to the variation in our DV.</p>
<p>This time we have an adjusted R-squared value of 0.918 - indicating that 91.8% of the variation in our DV can be explained by the IVs in our model. That is a considerable improvement on the 69.6% of the previous univariate model.</p>
<p>The intercept has moved to be -0.00342. The coefficient of EduScore is now 0.000729, meaning that a 1 unit change in the education score results in a 0.000729 change in the income deprivation score, in the same direction, when all other variables are held constant. We can also interpret the additional IV, employment deprivation score. This has a coefficient of 1.158 meaning that a 1 unit change in the employment deprivation score results in a 1.158 unit change in the income deprivation score, in the same direction, with all other variables being held constant. Again, this is a positive relationship, as the IV increases so will the DV.</p>
<p>We can once again plot some diagnostic plots for these models to see the spread of the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>IMD_2019 <span class="ot">&lt;-</span> IMD_2019 <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">predicted_multi =</span> <span class="fu">fitted</span>(multi_mod),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">residuals_multi =</span> <span class="fu">resid</span>(multi_mod)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>   )</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>Multi_Resids <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> residuals_multi)) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>   <span class="fu">labs</span>(</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">title =</span> <span class="st">"Residual Distribution"</span>,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">x =</span> <span class="st">"Residual"</span>,</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>   ) <span class="sc">+</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_minimal</span>()</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>Multi_rvf <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">x =</span> predicted_multi, <span class="at">y =</span> residuals_multi)) <span class="sc">+</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>   <span class="fu">labs</span>(</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">title =</span> <span class="st">"Residuals vs Fitted Values"</span>,</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">x =</span> <span class="st">"Fitted Values (Predicted Y)"</span>,</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> <span class="st">"Residuals (eᵢ)"</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>   )</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(Multi_Resids, Multi_rvf, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/multi%20diagnostics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This model has the residual density peak on zero and is much more symmetrical and the residuals vs fitted plot also shows that the model is homoskedastic - or that the error is roughly equal at both ends of the x-axis</p>
</section>
<section id="mapping-residuals-and-spatial-dependence" class="level3">
<h3 class="anchored" data-anchor-id="mapping-residuals-and-spatial-dependence">Mapping residuals and Spatial Dependence</h3>
<p>As touched on in the lecture, Linear Regression has a number of assumptions that should be met for reliable application. One of these is that the data is independent - an assumption that spatial data often violates. Although we <em>can</em> apply a linear regression model on spatial data, we should always check that the residuals of the model do not exhibit spatial autocorrelation. If they do that tells us that the model is systematically under-predicting in some places and over-predicting in others.</p>
<p>The first way to identify spatial patterning in the residuals of a model is to plot them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(IMD_2019, <span class="fu">aes</span>(<span class="at">fill =</span> residuals_multi)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">colours =</span> <span class="fu">brewer.pal</span>(<span class="dv">11</span>, <span class="st">"RdYlBu"</span>),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">rescale</span>(<span class="fu">quantile</span>(IMD_2019<span class="sc">$</span>residuals_multi,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">11</span>),</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                              <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"Residuals"</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals of Multivariate Regression Model"</span>,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"EduScore and EmpScore predicting IncScore"</span>,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: data.gov.uk"</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Introduction-to-Statistics_files/figure-html/plot%20resids-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this map we can see that areas of dark blue and dark red are often clustered together, in particular around London (positive residuals - model is under predicting in these areas) and the east coast of England (negative residuals - model is over predicting in these areas).</p>
<p>To test whether this spatial pattern is statistically relevant we need to calculate the Moran’s I statistic on the residuals as you did with Rich last time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"spdep"</span> <span class="sc">%in%</span> installed)) <span class="fu">install.packages</span>(<span class="st">"spdep"</span>, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(spdep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spdep</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>To access larger datasets in this package, install the spDataLarge
package with: `install.packages('spDataLarge',
repos='https://nowosad.github.io/drat/', type='source')`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>neighbours <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(IMD_2019, <span class="at">snap =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(IMD_2019, snap = 1): some observations have no neighbours;
if this seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>spweight <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(neighbours, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>moran <span class="ot">&lt;-</span> <span class="fu">moran.test</span>(IMD_2019<span class="sc">$</span>residuals_multi, spweight)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>moran</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  IMD_2019$residuals_multi  
weights: spweight  
n reduced by no-neighbour observations  

Moran I statistic standard deviate = 153.96, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     4.951762e-01     -2.960945e-05      1.034605e-05 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(moran<span class="sc">$</span>estimate[<span class="dv">1</span>]  <span class="sc">+</span> z <span class="sc">*</span> <span class="fu">sqrt</span>(moran<span class="sc">$</span>estimate[<span class="dv">3</span>]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.489 0.501</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">between</span>(moran<span class="sc">$</span>estimate[<span class="dv">2</span>], <span class="fl">0.489</span>, <span class="fl">0.501</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>As with Rich’s example from the previous week we have created a neighbours list, calculated a standardised weights matrix, calculated the Moran’s I statistic, calculated the confidence intervals and determined that the expected value is not between within the confidence values. This tells us that positive spatial autocorrelation exists within our residuals and therefore the results of a standard OLS linear regression model are not robust. We need to consider a way to manage the spatial autocorrelation within our model to ensure our predictions are valid across all locations.</p>
<p>Join Rich again in week 9 to begin discussing Geographically Weighted Regression!</p>
</section>
</section>
<section id="follow-up-exercise" class="level2">
<h2 class="anchored" data-anchor-id="follow-up-exercise">Follow Up Exercise</h2>
<p>For this short follow-up exercise,&nbsp;<strong>create a&nbsp;<em>simple</em>&nbsp;R markdown file</strong>&nbsp;(I suggest in HTML output format) that, when&nbsp;<em>knit</em>ted, includes the code and output for the following exercise.</p>
<p>The data you are being asked to analyse contains violent crime data for all of the Lower Super Output Areas (LSOAs) of London as well as some deprivation and demographic data for the populations of those LSOAs. Your tasks are as follows:</p>
<ul>
<li><p><strong>To download the following zipped folder and read the shapefile into R</strong>: <a href="https://github.com/BeckyCollinsBris/Mapping-and-Modelling-in-R---Intro-to-Statistics/raw/refs/heads/main/IMD_Crimezip.zip" class="uri">https://github.com/BeckyCollinsBris/Mapping-and-Modelling-in-R---Intro-to-Statistics/raw/refs/heads/main/IMD_Crimezip.zip</a></p></li>
<li><p><strong>To calculate some simple descriptive statistics of the dependent variable “Crime_rate”</strong></p></li>
<li><p><strong>To produce a cloropleth map of the dependent variable “Crime_rate”</strong> using your experiences from previous practicals</p></li>
<li><p><strong>To carry out a Spearmans correlation test between “Crime_rate” and the percentage of the population under the age of 23.</strong> Produce a scatter plot of the two variables against one another to accompany your pearson correlation and provide a short paragraph of interpretation.</p></li>
<li><p><strong>To create a univariate regression model of “Crime_rate” against the percentage of the population under the age of 23</strong>. Provide a paragraph of interpretation describing the intercept, slope estimate, R-squared value and p-value of the model.</p></li>
<li><p><strong>To create a multivariate regression model of “Crime_rate” against your choice of 3 variables from the dataset.</strong> Provide two paragraphs of accompanying text. One to describe why you have chosen those variables and a second to interpret the outcomes of your model</p></li>
</ul>
<p>The variable names have limits on their length so they are not always informative - a brief description of each variable is given below to help you achieve the above tasks.</p>
<p>LSOA - Lower Super Output Area - An administrative boundary used in the UK to provide a consistent geographical basis for collecting and reporting small-area statistics, such as those from the census.</p>
<p>Population - The population of this LSOA in 2019</p>
<p>Percent_ov - The percentage of the population over 65</p>
<p>Social_Ren - The percentage of the population living in social rented (or “council”) housing</p>
<p>MEAN_INCOM - The mean income of that LSOA in 2019</p>
<p>MEDIAN_INC - The median income of that LSOA in 2019</p>
<p>Crime_rate - The number of violent crimes per 1000 people recorded in 2019</p>
<p>IMD_RANK - The combined Index of Multiple Deprivation rank for that LSOA in 2019 (the lower the value the more deprived the area)</p>
<p>EMPLOYME_1 - The rank for that LSOA in 2019 based on the employment deprivation component of the IMD (the lower the value the more deprived the area)</p>
<p>EDUCATIO_1 - The rank for that LSOA in 2019 based on the education deprivation component of the IMD (the lower the value the more deprived the area)</p>
<p>Percent_U2 - The percentage of the population below 23</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>